
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author USER
 */
public class StudentIndividualInformation extends javax.swing.JFrame {

    private ResultSet result;
    private Statement ss;
    private Connection c;
    private PreparedStatement ps;

    /**
     * Creates new form StudentIndividualInformation
     */
    public StudentIndividualInformation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public int getWidth() { return super.getWidth(); }
    public int getHeight() { return super.getHeight(); }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        year = new javax.swing.JTextField();
        semester = new javax.swing.JTextField();
        department = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        bloodgrp = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fathersname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mothersname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cgpa = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        img1.setBackground(new java.awt.Color(153, 153, 153));
        img1.setForeground(new java.awt.Color(153, 153, 153));
        img1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(img1);
        img1.setBounds(610, 110, 210, 220);

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-undo-60.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(1003, 80, 100, 50);

        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(999, 20, 100, 30);

        year.setEditable(false);
        getContentPane().add(year);
        year.setBounds(200, 690, 250, 30);

        semester.setEditable(false);
        getContentPane().add(semester);
        semester.setBounds(730, 610, 250, 30);

        department.setEditable(false);
        getContentPane().add(department);
        department.setBounds(200, 610, 250, 30);

        gender.setEditable(false);
        getContentPane().add(gender);
        gender.setBounds(230, 310, 250, 30);

        bloodgrp.setEditable(false);
        getContentPane().add(bloodgrp);
        bloodgrp.setBounds(230, 270, 250, 30);

        dob.setEditable(false);
        getContentPane().add(dob);
        dob.setBounds(230, 232, 250, 30);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 102));
        jLabel8.setText("Personal Information -");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 50, 330, 38);

        jLabel13.setFont(new java.awt.Font("Yu Gothic Medium", 1, 32)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 102));
        jLabel13.setText("            Student Information");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(190, 0, 680, 50);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Name              : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 110, 150, 25);

        name.setEditable(false);
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(230, 110, 250, 30);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Father's Name  :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 150, 150, 25);

        fathersname.setEditable(false);
        getContentPane().add(fathersname);
        fathersname.setBounds(230, 150, 250, 30);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Mother's Name :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 190, 143, 25);

        mothersname.setEditable(false);
        getContentPane().add(mothersname);
        mothersname.setBounds(230, 190, 250, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("Date Of Birth    :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 230, 150, 25);

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 102));
        jLabel4.setText("Blood Group     :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 270, 150, 25);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("Gender             :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 310, 150, 25);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 102));
        jLabel12.setText("Mobile Number :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 350, 150, 25);

        mobile.setEditable(false);
        mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileActionPerformed(evt);
            }
        });
        getContentPane().add(mobile);
        mobile.setBounds(230, 350, 250, 30);

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("Email :");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(80, 400, 150, 25);

        email.setEditable(false);
        email.setForeground(new java.awt.Color(102, 102, 102));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(230, 400, 250, 30);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Address            :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 450, 150, 25);

        address.setEditable(false);
        getContentPane().add(address);
        address.setBounds(230, 450, 250, 50);

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 28)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 0, 102));
        jLabel14.setText("Academic Information -");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 540, 350, 38);

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("Department :");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(50, 610, 150, 25);

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("ID               : ");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(50, 650, 150, 25);

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 102));
        jLabel20.setText("Year            :");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(50, 690, 150, 25);

        id.setEditable(false);
        getContentPane().add(id);
        id.setBounds(200, 650, 250, 30);

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 102));
        jLabel21.setText("Semester     :");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(580, 610, 150, 25);

        cgpa.setEditable(false);
        getContentPane().add(cgpa);
        cgpa.setBounds(730, 650, 250, 30);

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 102));
        jLabel22.setText("CGPA          :");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(580, 650, 150, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background light blue.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1120, 1000);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(230, 310, 250, 30);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(230, 310, 250, 30);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(230, 310, 250, 30);

        setBounds(0, 0, 1139, 1039);
    }// </editor-fold>//GEN-END:initComponents
    public void image() throws SQLException, ClassNotFoundException {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_information_system", "root", "");
            String query = "select images from students_information";
            ss = c.createStatement();
            result = ss.executeQuery(query);
            while(result.next())
            {
                byte[] img = result.getBytes("images");
                //ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(img.getWidth(),img.getHeight(),Image.SCALE_SMOOTH));
                ImageIcon imageIcon = new ImageIcon(img);
                Image im = imageIcon.getImage();
                Image myimg = im.getScaledInstance(WIDTH,HEIGHT, Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(myimg);
                img1.setIcon(newImage);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //StudentLogInPage StudentLogInPage = new StudentLogInPage();
        //StudentLogInPage.setVisible(true);
        //this.dispose();
        SelectPage select = new SelectPage();
        select.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        try {
            AdminView admin = new AdminView();
            admin.setVisible(true);
            this.dispose();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StudentIndividualInformation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StudentIndividualInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentIndividualInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentIndividualInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentIndividualInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentIndividualInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentIndividualInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField address;
    private javax.swing.JButton back;
    public javax.swing.JTextField bloodgrp;
    public javax.swing.JTextField cgpa;
    public javax.swing.JTextField department;
    public javax.swing.JTextField dob;
    public javax.swing.JTextField email;
    public javax.swing.JTextField fathersname;
    public javax.swing.JTextField gender;
    public javax.swing.JTextField id;
    private javax.swing.JLabel img1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    public javax.swing.JTextField mobile;
    public javax.swing.JTextField mothersname;
    public javax.swing.JTextField name;
    public javax.swing.JTextField semester;
    public javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
